### ISSUE TITLE
[Survey] Move to Dedicated Database Schema

### ISSUE THREAD

**Issue by rkorszun** [opendexcom/formul.ai#78]
The Survey Service currently uses a shared schema. We want to move its data to a dedicated schema, e.g., `survey`, and ensure DDL (schema creation and migrations) are generated **only** for that schema.

---

### ✅ What You Need To Do

- [x] Update `application.yml` or `application.properties` to specify the schema:
  ```yaml
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/mydb
      hikari:
        schema: survey
    jpa:
      properties:
        hibernate:
          default_schema: survey
  ```
- [ ] Ensure Flyway/Liquibase is configured to manage the `survey` schema only:
  ```yaml
  flyway:
    schemas: survey
    defaultSchema: survey
  ```
- [ ] Move or rewrite migration scripts to operate inside the `survey` schema
- [ ] Test locally that:
  - Only the `survey` schema is touched
  - All DDL statements refer to the `survey` schema
- [ ] Clean up any leftover artifacts from the shared schema

---

### ✅ Acceptance Criteria

- Survey Service connects to and uses only the `survey` schema
- DDL and migrations apply **only** to the `survey` schema
- No operations affect or depend on other schemas

---

# 🔒 [Survey Service] Enforce Schema Isolation

Now that the Survey Service has its own schema, we want to enforce strict isolation — no queries, tables, or references to other schemas, and no accidental DDL leakage.

---

### ✅ What You Need To Do

- [ ] Check for any cross-schema references (e.g. `public.table_name`, foreign keys)
- [ ] Write a test or migration linter to validate all objects are within `survey` schema
- [ ] Configure Flyway (or your tool) to **fail** if any object is outside `survey`
- [ ] Ensure local and CI builds reflect only `survey` schema changes

---

### 🗃️ What is DDL (Data Definition Language)?

DDL is a subset of SQL (Structured Query Language) that is used to define or modify the structure of a database — for example: creating, altering, or deleting tables and their columns.

---

### ✅ Acceptance Criteria

- No cross-schema DDL or queries exist
- All generated DDL and migrations are scoped to `survey`
- CI build fails on violation
